---

- name: creating playbook for handlers
  hosts: all
  become: true
  tasks:
    - name: creating handler and notify
      copy:
        content: 'Hello Moto'
        dest: /tmp/abc.txt
      notify: apache_restart
  handlers:
    - name: apache_restart
      service:
        name: httpd
        state: restarted
        enabled: yes   
