- name: playbook for handler
  hosts: all
  become: true
  tasks:
    - name: creating notify 
      copy:
        content: 'hello world'
        dest: /tmp/abc.txt
      notify: apache_restart

  handlers:
    - name: apache_restart
      service:
        name: httpd
        state: restarted
        enabled: yes
  
