---
- name: creating playbook for handler
  hosts: all
  become : true
  tasks:
    - name: notify
      copy:
        content: "hello Pankaj"
        dest: /tmp/abc.txt
      notify: apache_restart

  handlers:
    - name: apache_restart
      service: 
        name: httpd
        state: restarted
        enabled: yes

