---
- name: creating playbook for handlers
  hosts: all
  become: true
  tasks:
    - name: copy content
      copy:
        content: "Hello world"
        dest: /tmp/pankaj.txt
        notify: restart_apache
  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted
        enabeled: yes
